### PR TITLE
slack app

### PR DESCRIPTION
**Pull request by ddkohler**
* new service `slack`
* Posts acquisition updates to a slack channel
* limited commands to select files for upload

### CODE REVIEW

**Comment by ksunden** [comment]
I would tend to think that this is actually something that shouldn't have a separate yaq daemon running, and just use the slack libraries here more directly.

I guess there are authentication things that would need to be sorted out, but I think that should be possible... just seems like adding a layer of indirection for no particular reason

I'd even perhaps consider adding this functionality to the wt5 container (perhaps behind some robustness checks to warn but not completely fail if it can't reach slack or isn't authenticated). This would allow easier access to eg include the images in slack posts like we used to do. As much as I like the idea of it being separable, that feature may be compelling.

**Comment by ddkohler** [comment]
@ksunden [my latest attempt](https://github.com/wright-group/bluesky-in-a-box/tree/test-slack-app-local) tries to run slack app and RE callbacks within a single container.  

A difficulty I'm running into is listening to both RE callbacks and slack events.  I'm struggling to get around Bluesky's RemoteDispatcher and slack's AsyncSocketModeHandler both running their own loops (which will trigger "RuntimeError:  Cannot run the event loop while another loop is running".  Do you know of any resources/ideas for getting around this?

**Comment by ddkohler** [comment]
The problem is starting both dispatcher and handler

https://github.com/wright-group/bluesky-in-a-box/blob/c15ac93e6a49e58921014ec5d706146569c05e0c/slack/slack_bot.py#L75-L81

**Comment by ddkohler** [comment]
apologies @ksunden, I am still learning with asyncio.  I now realize my loop issues are easily resolved.  Please disregard.

**Pull request merged**
