### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ddkohler**
uses environment variables for happi steps

### CODE REVIEW

**Comment by ksunden** [comment]
Can you test to see if the variable expands appropriately inside of the happi.ini file?

**Comment by ddkohler** [comment]
tried to use variable inside of ini, e.g.
```
path = %USERAPPDATA%\happi\happidb.json
```

I did not get it to work.  If you used a cli approach to write the ini, it could probably work

**Comment by ddkohler** [comment]
```
echo [DEFAULT] > %LOCALAPPDATA%\happi\happi\happi.ini
echo path = %LOCALAPPDATA%\happi\happi\happidb.json >> %LOCALAPPDATA%\happi\happi\happi.ini
```

**Comment by ksunden** [comment]
I leave it to you which is better

**Pull request merged**
