### PR TITLE
Update arch svg

### PR DESCRIPTION
**Pull request by ksunden**

### CODE REVIEW

**Comment by ksunden** [comment]
would be slightly more accurate to put the yaqc-bluesky and happi layers in the hwproxy box, but its such a minor part of the system that I didn't want to take the space for it, its already getting a bit crowded

**Comment by ddkohler** [comment]
> would be slightly more accurate to put the yaqc-bluesky and happi layers in the hwproxy box, but its such a minor part of the system that I didn't want to take the space for it, its already getting a bit crowded

So you are saying that yaqc-bluesky and happi are in the hwproxy container? I would vote for a correct diagram.  Besides, is it really getting more crowded?  You are just moving things around, not adding new things.  I'll leave the decision up to you though.

**Review by ddkohler — APPROVED** [review]

**Comment by ksunden** [comment]
happi and yaqc-bluesky would appear like they do for re-manager (we literally copy the same file, so technically wright-plans is also installed and imported, but it isn't used, so that much is incidental)

It is not removing them from re manager, it is adding them to hwproxy as well as keeping them in re-manager.

The crowding comes from having enough space for those to be labeled.

**Comment by ddkohler** [comment]
ok I misunderstood.  Looks like a good improvement.

**Pull request merged**
